### ISSUE TITLE
panos_security_rule - updates

### ISSUE THREAD

**Issue by fallenfuzz** [PaloAltoNetworks/ansible-pan#106]
Hi, few things would be great to have
_1. Option to place a rule on creation before and after specific rule and to move already existing rule before / after other rule. - Already in V1.0.7 as I see._

2. operation 'get' to list all / specific with tags or names rules with a call to a nice json
3. scheduling profile assignment (and of course option to create custom scheduling profile. not related to panos_security_rule  module, but still putting it here)

Thanks for your hard work!

**Comment by stealthllama** [comment]
The `location` parameter supports values of top, bottom, before, and after.  If no location is specified, the rule will be created at the bottom of the rule base.  If before or after are specified, an `existing_rule` parameter must be provided with a value of and existing rule name.

Can look into a separate config retrieval module but we cannot use the `operation` parameter any longer.  It's not "the Ansible way" of doing configuration management.  

Pull release #142 adds the `schedule` parameter (as a few others) to the `panos_security_rule` module.  A separate module will be needed for managing schedule profiles, but it will likely not happen soon.  The [pandevice](https://github.com/PaloAltoNetworks/pandevice) library that ansible-pan is built on doesn't support schedule objects yet.  Feel free to add an issue there requesting it.

**Comment by fallenfuzz** [comment]
Thanks!

**Comment by shinmog** [comment]
@fallenfuzz 

I think the only outstanding thing is an operation to get rules?  There are other github issues opened that are specific to that issue that I see if I just search for the word "rule", like #249, #248, #223....

Closing this issue; please feel free to jump in on any of these other more specific github issues so that we make sure we address your use-case (maybe #223 is the closest to what you're looking for..?).
