### ISSUE TITLE
Adding Objects can't assign a tag at same time?

### ISSUE THREAD

**Issue by troxil** [PaloAltoNetworks/ansible-pan#22]
Hello 

The panos_object task can't create new tags as well as assign the tag to an address object. 

I think tags or addresses need to be their own task instead. This can then be
1. Create tag
2. Create address object with tag above.

`{"changed": false, "failed": true, "msg": "parameters are mutually exclusive: ['addressobject', 'addressgroup', 'serviceobject', 'servicegroup', 'tag_name']"}`

Cheers,

**Comment by scott-abt** [comment]
The panos_object lets you create a few types of objects, which are all listed in the error message there. "tag_name" is actually the name of a tag object, I believe. Then you create a dynamic address group which has the filter criteria of your tag name, then use the panos_dag_tags task to create the ip -> tag mapping. 

Having said all that, I found your comment because I'm running into an issue with the panos_dag_tags task, so I can't say for sure that this is how its done.

**Comment by merewind** [comment]
any updates on tag issue?
