### ISSUE TITLE
Feature request: multiple modules commit = False

### ISSUE THREAD

**Issue by L1ghtman2k** [PaloAltoNetworks/ansible-pan#252]
I just thought it would be a cool feature if we were able to select whether or not we want to commit something right away like it is done by panos_interface

Module panos_zone commits by default, and there is no option to set it to false

Module panos_static_route does not commit by default, and there is no option to make it commit automatically

**Comment by shinmog** [comment]
@L1ghtman2k 

So, this is an interesting request because we've been wondering if we should remove the `commit` param from all modules.  The typical workflow is to configure multiple things and then do a commit at the end of that.  Having to have a `commit: false` in each task in that list is kind of annoying.

For your purposes, do you ever just run a single module?  Would you feel like something has been lost if we remove the `commit` param from all modules, thus requiring use of `panos_commit` at the end of your task list?

**Comment by L1ghtman2k** [comment]
Well, I think removing `commit` from all of the modules, and just making everything be committed at the end make sense, that would also emulate the interactions users have in GUI. Overall, I think no matter your final decision, I think what matters is consistency.

**Comment by shinmog** [comment]
@L1ghtman2k 

Ok, going to close this issue then, as I've stopped putting `commit` flags in newer modules.

When a user wants to commit something, they should just invoke `panos_commit` at the end of their playbooks.
