### ISSUE TITLE
Q: When to expect 1.0.7 to be ported to ansible? Thanks

### ISSUE THREAD

**Issue by fallenfuzz** [PaloAltoNetworks/ansible-pan#99]

**Comment by fallenfuzz** [comment]
Q is still relevant, any ideas?
2.6.1?

**Comment by shinmog** [comment]
After some discussion with RedHat, they have guided us to manage our Ansible modules using Ansible Galaxy roles instead of having them as part of ansible/ansible.  All modules that ship with ansible/ansible starting with Ansible version 2.8 will be deprecated and will guide users to install the PaloAltoNetworks.paloaltonetworks role instead.
